name:                ParBnC
version:             0.1.0.0
github:              "WeixiSilhouetteZed/ParBnC"
license:             BSD3
author:              "Weixi (Bill) Zhuo"
maintainer:          "wz2603@columbia.edu"
copyright:           "2022 Weixi (Bill) Zhuo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WeixiSilhouetteZed/ParBnC#readme>

dependencies:
- base >= 4.7 && < 5
- ieee754
- hmatrix
- parallel
- deepseq
- aeson
- bytestring
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ParBnC-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ParBnC

tests:
  ParBnC-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ParBnC
